@OneIdentity.Homework.Api_HostAddress = http://localhost:5200/api

GET {{OneIdentity.Homework.Api_HostAddress}}/users
Accept: application/json

###

GET {{OneIdentity.Homework.Api_HostAddress}}/users/152f5133-000d-4a75-b67a-aa359decae39?ps=10&pn=0
Accept: application/json

###

POST {{OneIdentity.Homework.Api_HostAddress}}/users/
Accept: text/plain
Content-Type: application/json

{
  "Id": "152f5133-000d-4a75-b67a-aa359decae39",
  "UserName" : "SomeName",
  "Password" : "Password",
  "Email" : "dumy@email.com",
  "BirthDate" : "2023-05-10",
  "PhoneNumber" : "+36 30 6666666",
  "Nickname" : "nickname"
}

###

PUT {{OneIdentity.Homework.Api_HostAddress}}/users/152f5133-000d-4a75-b67a-aa359decae39
Accept: text/plain
Content-Type: application/json

{
  "Email" : "dumy@email.com",
  "BirthDate" : "2023-05-10",
  "PhoneNumber" : "+36 30 5555555",
  "Nickname" : "nickname"
}

###

DELETE {{OneIdentity.Homework.Api_HostAddress}}/users/152f5133-000d-4a75-b67a-aa359decae39
Accept: application/json

###

