# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Build, test, sonar"

permissions:
  id-token: write
  contents: read
  checks: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch :

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # for sonar
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup Aspire
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: | 
          dotnet restore
          dotnet tool restore
    - name: SonarCloud Begin
      run: dotnet sonarscanner begin /o:sevenver /k:sevenver12_one-identity-home-work /d:sonar.login=${{ secrets.SONAR_TOKEN }} /s:$GITHUB_WORKSPACE/.config/SonarQube.Analysis.xml
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage;Format=opencover" --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
    - name: SonarCloud End
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true